FROM node:10.15.2-alpine

# Create app directory
WORKDIR /usr/src/app

RUN apk add graphicsmagick
RUN apk add imagemagick


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./

RUN npm install
RUN npm run postinstall
# If you are building your code for development
# RUN npm install --only=development

# Bundle app source
COPY . .

EXPOSE 8000
CMD [ "npm", "run", "start:prod" ]
